# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170601_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publication_date',
            new_name='pub_date',
        ),
    ]
