# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170602_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
